name: is this glitchy too
favicon: null
layout_spectrum: 0.15563086094334722
typography_spectrum: 0.11584129091352224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.44812542060390115
  lightness: 0.6375817318912596
  saturation: 0.568833215162158
  rhythmicContrast: 0.22353272535838187
purpose: []
